### ISSUE TITLE
Советы по оформлению кода

### ISSUE THREAD

**Issue by kirillEvstrat** [graschik/ViewingJokes#1]
Замечания:
1)Стили должны быть описаны в отдельном css файле.
2)Следует при использовании шаблонизатора Twig называть переменные так, чтобы можно было однозначно понять, что именно вставляется в макет.
3)В некоторых местах код не соответсвует стандартам. Советую изучить стандарты PSR-1, PSR-2, PSR-3, PSR-4. А именно:
   - Для оформления отступов ДОЛЖНЫ использоваться четыре пробела.
   - После открывающей круглой скобки и перед закрывающей круглой скобкой в управляющих конструкциях НЕ ДОЛЖНО быть пробела. (FormHandler.php)
   -В конце каждого файла с PHP-кодом должна быть одна пустая строка.
Закрывающий тег ?> должен отсутствовать в файлах, содержащих только PHP-код

       Из плюсов:
1) Понятное разделение кода по классам и namespace.
2) Общая читаемость кода.
3) Комментарии.
4) Использование strict_types.

**Comment by graschik** [comment]
> ```
>    Замечания:
> ```
> 1)Стили должны быть описаны в отдельном css файле.
> 2)Следует при использовании шаблонизатора Twig называть переменные так, чтобы можно было однозначно понять, что именно вставляется в макет.
> 3)В некоторых местах код не соответсвует стандартам. Советую изучить стандарты PSR-1, PSR-2, PSR-3, PSR-4. А именно:
> 
> * Для оформления отступов ДОЛЖНЫ использоваться четыре пробела.
> * После открывающей круглой скобки и перед закрывающей круглой скобкой в управляющих конструкциях НЕ ДОЛЖНО быть пробела. (FormHandler.php)
>   -В конце каждого файла с PHP-кодом должна быть одна пустая строка.
>   Закрывающий тег ?> должен отсутствовать в файлах, содержащих только PHP-код
>   Из плюсов:
> 
> 1. Понятное разделение кода по классам и namespace.
> 2. Общая читаемость кода.
> 3. Комментарии.
> 4. Использование strict_types.

Все замечания были учтены и исправлены.
